apiVersion: v1
kind: ConfigMap
metadata:
  name: awstoazure-config
  namespace: awstoazure-prod
  labels:
    app: awstoazure
data:
  application.properties: |
    server.port=8080
    spring.application.name=awstoazure
    management.endpoints.web.exposure.include=health,info,prometheus
    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    logging.level.com.example=INFO
    logging.level.org.springframework=INFO
